// Generated by gencpp from file my_pkg/srv1.msg
// DO NOT EDIT!


#ifndef MY_PKG_MESSAGE_SRV1_H
#define MY_PKG_MESSAGE_SRV1_H

#include <ros/service_traits.h>


#include <my_pkg/srv1Request.h>
#include <my_pkg/srv1Response.h>


namespace my_pkg
{

struct srv1
{

typedef srv1Request Request;
typedef srv1Response Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct srv1
} // namespace my_pkg


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::my_pkg::srv1 > {
  static const char* value()
  {
    return "2a5c7a37218262bae4fcfaa1007692aa";
  }

  static const char* value(const ::my_pkg::srv1&) { return value(); }
};

template<>
struct DataType< ::my_pkg::srv1 > {
  static const char* value()
  {
    return "my_pkg/srv1";
  }

  static const char* value(const ::my_pkg::srv1&) { return value(); }
};


// service_traits::MD5Sum< ::my_pkg::srv1Request> should match
// service_traits::MD5Sum< ::my_pkg::srv1 >
template<>
struct MD5Sum< ::my_pkg::srv1Request>
{
  static const char* value()
  {
    return MD5Sum< ::my_pkg::srv1 >::value();
  }
  static const char* value(const ::my_pkg::srv1Request&)
  {
    return value();
  }
};

// service_traits::DataType< ::my_pkg::srv1Request> should match
// service_traits::DataType< ::my_pkg::srv1 >
template<>
struct DataType< ::my_pkg::srv1Request>
{
  static const char* value()
  {
    return DataType< ::my_pkg::srv1 >::value();
  }
  static const char* value(const ::my_pkg::srv1Request&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::my_pkg::srv1Response> should match
// service_traits::MD5Sum< ::my_pkg::srv1 >
template<>
struct MD5Sum< ::my_pkg::srv1Response>
{
  static const char* value()
  {
    return MD5Sum< ::my_pkg::srv1 >::value();
  }
  static const char* value(const ::my_pkg::srv1Response&)
  {
    return value();
  }
};

// service_traits::DataType< ::my_pkg::srv1Response> should match
// service_traits::DataType< ::my_pkg::srv1 >
template<>
struct DataType< ::my_pkg::srv1Response>
{
  static const char* value()
  {
    return DataType< ::my_pkg::srv1 >::value();
  }
  static const char* value(const ::my_pkg::srv1Response&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MY_PKG_MESSAGE_SRV1_H
