// Generated by gencpp from file my_pkg/srv2Response.msg
// DO NOT EDIT!


#ifndef MY_PKG_MESSAGE_SRV2RESPONSE_H
#define MY_PKG_MESSAGE_SRV2RESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace my_pkg
{
template <class ContainerAllocator>
struct srv2Response_
{
  typedef srv2Response_<ContainerAllocator> Type;

  srv2Response_()
    : multiply(0)  {
    }
  srv2Response_(const ContainerAllocator& _alloc)
    : multiply(0)  {
  (void)_alloc;
    }



   typedef int32_t _multiply_type;
  _multiply_type multiply;





  typedef boost::shared_ptr< ::my_pkg::srv2Response_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::my_pkg::srv2Response_<ContainerAllocator> const> ConstPtr;

}; // struct srv2Response_

typedef ::my_pkg::srv2Response_<std::allocator<void> > srv2Response;

typedef boost::shared_ptr< ::my_pkg::srv2Response > srv2ResponsePtr;
typedef boost::shared_ptr< ::my_pkg::srv2Response const> srv2ResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::my_pkg::srv2Response_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::my_pkg::srv2Response_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::my_pkg::srv2Response_<ContainerAllocator1> & lhs, const ::my_pkg::srv2Response_<ContainerAllocator2> & rhs)
{
  return lhs.multiply == rhs.multiply;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::my_pkg::srv2Response_<ContainerAllocator1> & lhs, const ::my_pkg::srv2Response_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace my_pkg

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::my_pkg::srv2Response_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::my_pkg::srv2Response_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::my_pkg::srv2Response_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::my_pkg::srv2Response_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::my_pkg::srv2Response_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::my_pkg::srv2Response_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::my_pkg::srv2Response_<ContainerAllocator> >
{
  static const char* value()
  {
    return "6beb9d0eae755804051c303fd583c637";
  }

  static const char* value(const ::my_pkg::srv2Response_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x6beb9d0eae755804ULL;
  static const uint64_t static_value2 = 0x051c303fd583c637ULL;
};

template<class ContainerAllocator>
struct DataType< ::my_pkg::srv2Response_<ContainerAllocator> >
{
  static const char* value()
  {
    return "my_pkg/srv2Response";
  }

  static const char* value(const ::my_pkg::srv2Response_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::my_pkg::srv2Response_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 multiply\n"
;
  }

  static const char* value(const ::my_pkg::srv2Response_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::my_pkg::srv2Response_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.multiply);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct srv2Response_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::my_pkg::srv2Response_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::my_pkg::srv2Response_<ContainerAllocator>& v)
  {
    s << indent << "multiply: ";
    Printer<int32_t>::stream(s, indent + "  ", v.multiply);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MY_PKG_MESSAGE_SRV2RESPONSE_H
