// Generated by gencpp from file path_schedule/path_plan_service.msg
// DO NOT EDIT!


#ifndef PATH_SCHEDULE_MESSAGE_PATH_PLAN_SERVICE_H
#define PATH_SCHEDULE_MESSAGE_PATH_PLAN_SERVICE_H

#include <ros/service_traits.h>


#include <path_schedule/path_plan_serviceRequest.h>
#include <path_schedule/path_plan_serviceResponse.h>


namespace path_schedule
{

struct path_plan_service
{

typedef path_plan_serviceRequest Request;
typedef path_plan_serviceResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct path_plan_service
} // namespace path_schedule


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::path_schedule::path_plan_service > {
  static const char* value()
  {
    return "a492be626b9e9035dc3f45a07b0259c0";
  }

  static const char* value(const ::path_schedule::path_plan_service&) { return value(); }
};

template<>
struct DataType< ::path_schedule::path_plan_service > {
  static const char* value()
  {
    return "path_schedule/path_plan_service";
  }

  static const char* value(const ::path_schedule::path_plan_service&) { return value(); }
};


// service_traits::MD5Sum< ::path_schedule::path_plan_serviceRequest> should match
// service_traits::MD5Sum< ::path_schedule::path_plan_service >
template<>
struct MD5Sum< ::path_schedule::path_plan_serviceRequest>
{
  static const char* value()
  {
    return MD5Sum< ::path_schedule::path_plan_service >::value();
  }
  static const char* value(const ::path_schedule::path_plan_serviceRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::path_schedule::path_plan_serviceRequest> should match
// service_traits::DataType< ::path_schedule::path_plan_service >
template<>
struct DataType< ::path_schedule::path_plan_serviceRequest>
{
  static const char* value()
  {
    return DataType< ::path_schedule::path_plan_service >::value();
  }
  static const char* value(const ::path_schedule::path_plan_serviceRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::path_schedule::path_plan_serviceResponse> should match
// service_traits::MD5Sum< ::path_schedule::path_plan_service >
template<>
struct MD5Sum< ::path_schedule::path_plan_serviceResponse>
{
  static const char* value()
  {
    return MD5Sum< ::path_schedule::path_plan_service >::value();
  }
  static const char* value(const ::path_schedule::path_plan_serviceResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::path_schedule::path_plan_serviceResponse> should match
// service_traits::DataType< ::path_schedule::path_plan_service >
template<>
struct DataType< ::path_schedule::path_plan_serviceResponse>
{
  static const char* value()
  {
    return DataType< ::path_schedule::path_plan_service >::value();
  }
  static const char* value(const ::path_schedule::path_plan_serviceResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // PATH_SCHEDULE_MESSAGE_PATH_PLAN_SERVICE_H
